const config = require('creep.config');

/**
 * Counts all creeps, where key is role and value is count
 *
 * @example {
 *  gather: 2
 * }
 */
function countCreeps(creeps) {
    const creepCount = {};
    for (const i in creeps) {
        const c = creeps[i];
        const { role } = c.memory;
        if (!role) {
            console.log(`No role for ${c.name}`);
            continue;
        }

        creepCount[role] = creepCount[role] ? creepCount[role]++ : 1;
    }

    console.log(JSON.stringify(creepCount));
    return creepCount;
}

const names = [
    'EatBullets',
    'PR0_GGRAM3D',
    'CollateralDamage',
    'TheSickness',
    'Shoot2Kill',
    'Overkill',
    'Killspree',
    'MindlessKilling',
    'Born2Kill',
    'TheZodiac',
    'ZodiacKiller',
    'Osamaisback',
    'OsamasGhost',
    'T3rr0r1st',
    'ToySoldier',
    'MilitaryMan',
    'DeathSquad',
    'Veteranofdeath',
    'Angelofdeath',
    'Ebola',
    'MustardGas',
    'Knuckles',
    'KnuckleBreaker',
    'KnuckleDuster',
    'BloodyKnuckles',
    'JackTheRipper',
    'TedBundyHandsome',
    'Necromancer',
    'SmilingSadist',
    'ManicLaughter',
    'Tearsofjoy',
    'ShowMeUrguts',
    'KnifeInGutsOut',
    'Talklesswinmore',
    'Guillotine',
    'Decapitator',
    'TheExecutor',
    'BigKnives',
    'SharpKnives',
    'LocalBackStabber',
    'BodyParts',
    'BodySnatcher',
    'TheButcher',
    'meat cleaver',
    'ChopChop',
    'ChopSuey',
    'TheZealot',
    'VagaBond',
    'LoneAssailant',
    '9mm',
    'SemiAutomatic',
    '101WaysToMeetYourMaker',
    'SayHi2God',
    'Welcome2Hell',
    'HellNBack',
    'Dudemister',
    'MiseryInducing',
    'SmashDtrash',
    'TakinOutThaTrash',
    'StreetSweeper',
    'TheBully',
    'Getoutofmyway',
    'NoMercy4TheWeak',
    'Sl4ught3r',
    'HappyKilling',
    'HappyPurgeDay',
    'HappyPurging',
    'RiotStarter',
    'CantStop',
    'CantStopWontstop',
    'SweetPoison',
    'SimplyTheBest',
    'PuppyDrowner',
    'EatYourHeartOut',
    'RipYourHeartOut',
    'BloodDrainer',
    'AcidAttack',
    'AcidFace',
    'PetrolBomb',
    'Molotov',
    'TequilaSunrise',
    'TeKillaSunrise',
    'LocalGrimReaper',
    'SoulTaker',
    'DreamHaunter',
    'Grave Digger',
    'YSoSerious',
    'Revenge',
    'Avenged',
    'BestServedCold',
    'HitNRUN',
    'Fastandfurious',
    'MrBlond',
    'TheKingIsDead',
    'TheNihilist',
    'Bad2TheBone',
    'OneShot',
    'SmokinAces',
    'DownInSmoke',
    'NoFun4U',
    '101WaysToMeetYourMaker',
    '3D Waffle',
    '44',
    '57 Pixels',
    'Accidental Genius',
    'Acid Gosling',
    'Admiral Tot',
    'AgentHercules',
    'Airport Hobo',
    'Alley Frog',
    'Alpha',
    'AlphaReturns',
    'Angel',
    'AngelsCreed',
    'Arsenic Coo',
    'Atomic Blastoid',
    'Automatic Slicer',
    'Baby Brown',
    'Back Bett',
    'Bad Bunny',
    'Bazooka Har-de-har',
    'Bearded Angler',
    'Beetle King',
    'Betty Cricket',
    'Bit Sentinel',
    'Bitmap',
    'BlacKitten',
    'Blister',
    'Blistered Outlaw',
    'Blitz',
    'BloodEater',
    'Bonzai',
    'BoomBeachLuvr',
    'BoomBlaster',
    'Bootleg Taximan',
    'Bowie',
    'Bowler',
    'Breadmaker',
    'Broomspun',
    'Buckshot',
    'Bug Blitz',
    'Bug Fire',
    'Bugger',
    'Cabbie',
    'Candy Butcher',
    'Capital F',
    'Captain Peroxide',
    'Celtic Charger',
    'Centurion Sherman',
    'Cereal Killer',
    'Chasm Face',
    'Chew Chew',
    'Chicago Blackout',
    'Chip Queen',
    'ChocoNutsX',
    'Chocolate Thunder',
    'Chuckles',
    'Club Nola',
    'CoB@lt',
    'CobraBite',
    'Cocktail',
    'CollaterolDamage',
    'CommandX',
    'Commando',
    'Congo Wire',
    'Cool Iris',
    'Cool Whip',
    'Cosmo',
    'Crash Override',
    'Crash Test',
    'Crazy Eights',
    'Criss Cross',
    'Cross Thread',
    'Cujo',
    'Cupid Dust',
    'Daffy Girl',
    'Dahlia Bumble',
    'DaisyCraft',
    'Dancing Madman',
    'Dangle',
    'DanimalDaze',
    'Dark Horse',
    'Darkside Orbit',
    'Darling Peacock',
    'Day Hawk',
    'Desert Haze',
    'Desperado',
    'Devil Blade',
    'Devil Chick',
    'Dexter',
    'Diamond Gamer',
    'Digger',
    'Disco Potato',
    'Disco Thunder',
    'DiscoMate',
    'Don Stab',
    'Doz Killer',
    'Dredd',
    'DriftDetector',
    'DriftManiac',
    'Drop Stone',
    'Dropkick',
    'Drugstore Cowboy',
    'DuckDuck',
    'Earl of Arms',
    'Easy Sweep',
    'Eerie Mizzen',
    'ElactixNova',
    'Elder Pogue',
    'Electric Player',
    'Electric Saturn',
    'Ember Rope',
    'Esquire',
    'ExoticAlpha',
    'EyeShooter',
    'Fabulous',
    'Fast Draw',
    'FastLane',
    'Father Abbot',
    'FenderBoyXXX',
    'Fennel Dove',
    'Feral Mayhem',
    'Fiend Oblivion',
    'FifthHarmony',
    'Fire Feline',
    'Fire Fish',
    'FireByMisFire',
    'Fist Wizard',
    'Flakes',
    'Flame OUT',
    'Flint',
    'FlyGuardX',
    'Flying Doodle',
    'FrankenGrin',
    'Freak',
    'Frozen Explosion',
    'Gadget',
    'Gas Man',
    'General Broomdog',
    'General Finish',
    'Ghostrider',
    'Global meltdown',
    'Glyph',
    'Goatee Shield',
    'Gov Skull',
    'Grave Digger',
    'Greek Rifle',
    'Green Ghost',
    'Green Scavenger',
    'Guillotine',
    'Gullyway',
    'Guncap Slingbad',
    'Gunhawk',
    'HeroOfBlackday',
    'High Kingdom Warrior',
    'Highlander Monk',
    'Hightower',
    'Hog Butcher',
    'HollySparta',
    'Houston',
    'Houston Rocket',
    'Hyper',
    'Hyper Kong',
    'Impulsive Flower',
    'Indiana',
    'IonicHound',
    'Jack Cassidy',
    'Jelly Camber',
    'Jester',
    'JesterZilla',
    'JigKraken',
    'Jigsaw',
    'Joker’s Grin',
    'Judge',
    'Junkyard Dog',
    'K-9',
    'K-Tin Man',
    'Keystone',
    'KiTParty',
    'Kickstart',
    'Kill Switch',
    'Killah Goose',
    'Kingfisher',
    'KingofWolfstreet',
    'Kitchen',
    'Knight Light',
    'Knuckles',
    'Koi Diva',
    'LFAKing',
    'Lady Killer',
    'Landfill Max',
    'Lava Nibbler',
    'Lazy Killer',
    'LeSpank',
    'LexusGTXXX',
    'LifeRobber',
    'Light Lion',
    'LightInOut',
    'Liquid Death',
    'Liquid Science',
    'Little Cobra',
    'Little General',
    'LittleTickle',
    'Lope Lope',
    'Lord Nikon',
    'Lord Pistachio',
    'Lord Theus',
    'Lucifer%u2019s rain',
    'Lucky',
    'LunaStar',
    'Lunar Treat',
    'Mad Irishman',
    'Mad Jack',
    'Mad Kid',
    'Mad Rascal',
    'Mad Robin',
    'ManMaker',
    'Manimal',
    'Marbles',
    'Marigold Loot',
    'Married Man',
    'MarshalKing',
    'Marshmallow',
    'MaxicanChoncho',
    'MeetWit',
    'Mental',
    'Mercury Reborn',
    'Metal Star',
    'Midas',
    'Midnight Rambler',
    'Midnight Rider',
    'MightyFellow',
    'MindBuggle',
    'Mindless Bobcat',
    'Mint Ness',
    'MonkeyKing',
    'MonkeySmash',
    'MonsterMania',
    'Moon Solitaire',
    'Mud Pie Man',
    'Mule Skinner',
    'Mum Mary',
    'Murmur',
    'Mustang',
    'MysteryEnds',
    'Mystic',
    'Nacho',
    'Natural Gold',
    'Natural Mess',
    'Necromancer',
    'NemesisX',
    'Neophyte Believer',
    'Nessie',
    'New Cycle',
    'New York Winder',
    'Nickname Master',
    'Night Magnet',
    'Night Train',
    'Nightmare King',
    'NoiseFire',
    'Nutmeg Riot',
    'Old Man Winter',
    'Old Orange Eyes',
    'Old Regret',
    'Omega Sub',
    'Onion King',
    'Osprey',
    'Overrun',
    'Papa Smurf',
    'Paradise',
    'Pearl Girl',
    'Pepper Legs',
    'Peppermint',
    'Phoenix Tetra',
    'PhoenixHeat',
    'Pinball Wizard',
    'Pink Hopper',
    'PinkFloyd',
    'PinkPanther',
    'Pistol Hydro',
    'Pixie Soldier',
    'Pluto',
    'Pogue',
    'Polar Bee',
    'Poppy Coffee',
    'Poptart AK47',
    'Prometheus',
    'Psycho Thinker',
    'Pusher',
    'Racy Lion',
    'RadioactiveMan',
    'Raid Bucker',
    'Rando Tank',
    'Ranger',
    'Red Combat',
    'Red Rhino',
    'RedFeet',
    'RedFisher',
    'RedMouth',
    'Reed Lady',
    'Renegade Slugger',
    'Reno Monarch',
    'Returns',
    'RevengeOfOmega',
    'Riff Raff',
    'Roadblock',
    'RoarSweetie',
    'Rocky Highway',
    'Roller Turtle',
    'Romance Guppy',
    'Rooster',
    'Rude Sniper',
    'Saint La-Z-Boy',
    'Sandbox',
    'Scare Stone',
    'ScaryNinja',
    'ScaryPumpkin',
    'Scrapper',
    'Scrapple',
    'Screw',
    'Screwtape',
    'Seal Snake',
    'Sexual Chocolate',
    'Shadow Bishop',
    'Shadow Chaser',
    'Sherwood Gladiator',
    'Shooter',
    'ShowMeSunset',
    'ShowMeUrguts',
    'Sidewalk Enforcer',
    'Sienna Princess',
    'Silver Stone',
    'Sir Shove',
    'Skull Crusher',
    'Sky Bully',
    'Sky Herald',
    'Slow Trot',
    'SmartieQuest',
    'SmashBuster',
    'SmashDtrash',
    'Snake Eyes',
    'SnakeEye',
    'SniperInstinct',
    'SnoopWoot',
    'Snow Cream',
    'Snow Hound',
    'Snow Pharaoh',
    'SnowWhiteLuvr',
    'Sofa King',
    'Solo Kill',
    'SpeedBreaker',
    'Speedwell',
    'SpellTansy',
    'Spider Fuji',
    'Spike',
    'SpitFire',
    'Spooky Yellowjacket',
    'Springheel Jack',
    'Spunky Comet',
    'Spy',
    'Squatch',
    'Stacker of Wheat',
    'Stallion Patton',
    'Star Sword',
    'Station WMD',
    'Street Squirrel',
    'Subzero Taffy',
    'Sugar Man',
    'Suicide Jockey',
    'Sultan of Speed',
    'SunVolt',
    'Swampmasher',
    'Sweet Talker',
    'Swerve',
    'SwiftFox',
    'SwiftSpeed',
    'TWitMeet',
    'Tacklebox',
    'Take Away',
    'Tan Stallion',
    'TecTonic',
    'Terror Master',
    'Thanksgiving',
    'The China Wall',
    'The Dude',
    'The Final Judgement',
    'The Flying Mouse',
    'The Happy Jock',
    'The Howling Swede',
    'The Shield Toronto',
    'Third Moon',
    'Thrasher',
    'ThunderStroke',
    'Toe',
    'Toolmaker',
    'Tough Nut',
    'ToxicCharger',
    'Toy Dogwatch',
    'Trash Master',
    'Trash Sling',
    'Trick Baron',
    'Trip',
    'TrixiePhany',
    'Troubadour',
    'TulipCake',
    'Turnip King',
    'Twin Blaze',
    'Twinkle Cutlass',
    'Twitch',
    'Twix Bond',
    'UCantBeatIt',
    'Uncle Psycho',
    'Vagabond Warrior',
    'VenusLion',
    'VenusQueen',
    'Vicious Street',
    'Voluntary',
    'Vortex',
    'Washer',
    'Waylay Dave',
    'Wheels',
    'White Snare',
    'Wholesome',
    'Widow Curio',
    'Willow Dragon',
    'WindyGod',
    'Winter Bite',
    'Wolf Tribune',
    'Wolverine',
    'Woo Woo',
    'Wooden Man',
    'Yellow Menace',
    'Zero Charisma',
    'Zesty Dragon',
    'Zod',
    'Type2Diabetes',
    'Yellow Snowman',
    'FartinLutherKing',
    'I have a large sock',
    'Milf n cookies',
    'WestboroFaptist',
    'IRTEHBEST',
    'SumDumFuk',
    'SLUTB6NGER66',
    'InfantFister69',
    'Fistersister',
    'fisting grannies',
    'FistMeSis',
    'Fisting Sloth',
    'Livingabortion',
    'Floatyturd',
    'Pooponmyballs',
    'PoopFinger',
    'Parts',
    'Whackingit',
    'sum az whole',
    'A55 Kicken Chicken',
    'HorseScrotom',
    'Sausage',
    'hairy sausage',
    'Your Mother',
    'Count Asscrackula',
    'Happy Uncle',
    'Dr Cocktopus',
    'PullOutDad',
    'I Eated a Soup',
    'REVEREND TOAST',
    'Rev Fondlechild',
    'ButtCabbage',
    'Itchy Bits',
    'Jerkoff',
    'A side of Ham',
    'AirIsWindy',
    'A Confused shoe',
    'Toiletpaperman',
    'MOMS SPAGHETTI',
    'Milfhunter',
    'xXyoloswag4jesusXx',
    'LilChubby',
    'GaryBuseysteeth',
    'OuchHardFart',
    'CourtesyFlush',
    'Thermostat',
    'WookiesrPpl2',
    'LtDansLegs',
    'ThePopesLube',
    'WINDOWCLEANer',
    'SwishyMcJackass',
    'Pwn_Dolphins_Drink_Beer',
    'I_Like_Cheese',
    'Burrito',
    'An18inchDildo',
    'BeerAndCookies',
    'I_Be-B1azin',
    'WEED_IS_FOR_LOSERS',
    'xBongsmoker420x',
    'Bongsta',
    'Gongsta',
    'Teriyaki Bukake',
    'BrosephStalin',
    'Ichyb3ll',
    'Six nippled yehti',
    'GassyJalapeno',
    'TwoTugTonyTheFapMaster',
    'Bad Grandpa',
    'ForcefulGrandpa',
    'PleasenoDad',
    'Beefstrokemeoff',
    'Boobguy45',
    'VulvaViolator',
    'GayZebrasUnite',
    'My Ball Sack',
    'Barry Hallsacks',
    'I Lick Hobos',
    'Freeponyride',
    'Cancer',
    'IAbuseMyFish',
    'DadsButtjuice',
    'A Harmless Cupcake',
    'a giant 8llllllD',
    'ATastySandwich',
    'WifeTookMyDog',
    'The US Debt',
    'Abs of flab',
    'Moistgranny69',
    'Count Swagula',
    'Turdinator',
    'RektalBead',
    'Pulloutfailure',
    'Facefart',
    'Syphilis',
    'StankFartass',
    'Sh3Wuz18',
    'BedBathNurMom',
    'A CARDBOARDBOX',
    'TerminatorT800',
    'Get2ThaChopper',
    'Ronald Raygun',
    'some hippies',
    'TwoOreosOneCup',
    'chimp magnet',
    'StrangerDanger',
    'a better player',
    'Chris_P_Bacon',
    'TuckingFypo',
    'An L Shaped Tetris Block',
    'Osama_Been_Laggin',
    'PeekaBooOsamaSeeU',
    'About 37 cats',
    'About76mexicans',
    'Slagathor',
    'Statutory Ape',
    'IfISuckItsMyDad',
    'NoMomICantPauseIt',
    '8-6-7-5-3-0-9',
    'FusterCluck',
    'AlphaQ',
    'Bilboteabaggins',
    'GrammerNazi',
    'Asmallbaby',
    'A baby Seal',
    'A Helpless Fetus',
    'A_Falling_Body',
    'Gnome Saying',
    'Barles Charkley',
    'Phuck Yuu',
    'Il Phuck Yuu',
    'A flying lemon',
    'Dudefella',
    'Use Preparation H',
    'Tank Sinatra',
    'Deleted User',
    'TomCruisin',
    'The Easter Bunny',
    'Lt MorningWood',
    'HanSoloDies',
    'ObiWanCanBlowMe',
    'GonnaMakeUQuit',
    'Haywoodugofuhkurself',
    'SonicTheHedgefund',
    'Oh-so-damn-smart',
    'FileURComplaint',
    'PartyInTheUSSRx',
    'xxlookXatXmyXs',
    'Party_McFly',
    'about 5 ninjas',
    'Asasinsensation',
    'ninja typhoOon',
    'ScaryNinja',
    'NinjaHype',
    'Shuriken',
    'NinjaStar',
    'EnterTheNinja',
    'EnterTheDragon',
    'Metsubishi',
    'Pandas',
    'OpaqueNinja',
    'Manriki-gusari',
    'NinjaMan',
    'NinjaDude',
    'Silent assassin',
    'Kunai',
    'Ninjah',
    'TwoKatanas',
    'KatanaIfyawanna',
    'KantanaSlice',
    'KantanaOnToast',
    'Precursorninja',
    'NinjaSkills',
    'Skillslikeaninja',
    'NinjaOnFire',
    'Fukiya',
    'Ninja Maneuver',
    'Ninjamoves',
    'Ninja Pwnage',
    'Neko Te',
    'NekoTeGirl',
    'NekoTeClaws',
    'NinjaWithWings',
    'TMNT',
    'Shredder',
    'Justturtles',
    'Kakute',
    'NinjaSchool',
    'NowYouSeeMe',
    'Kusarigama',
    'Wayofthewarrior',
    'Callmesensei',
    'Samureye',
    'SamuraiJack',
    'ShadowFriend',
    'ShadowFiend',
    'CrouchingTiger',
    'Whatisninja',
    'Ninjutsu',
];

/**
 * Creates a new creep, with a random name
 *
 * @param {string}  role  The designated role for the creep e.g. 'gather'
 * @param {string[]} parts  The parts the creep should be made of
 * @param {*} spawner
 */
function spawnNewCreep(role, parts, spawner) {
    if (spawner.spawning) {
        return;
    }
    console.log(`Spawning: ${role}`);
    spawner.spawnCreep(
        parts,
        names[Math.floor(Math.random() * names.length)],
        {
            memory: {
                role,
            },
        },
    );
}

/**
 * Checks if we need to spawn new creeps
 *
 * @param {StructureSpawn}  spawner the spawner in a room
 * @returns
 */
function checkForSpawn(spawner) {
    const roomCreeps = spawner.room.find(FIND_MY_CREEPS);
    const currentRoleCounts = countCreeps(roomCreeps);
    const toSpawn = {};
    for (const role in config) {
        const roleConfig = config[role];
        roleConfig.name = role;
        const currentCreepCount = currentRoleCounts[role] || 0;
        if (toSpawn.creepCount === undefined || !toSpawn.role) {
            toSpawn.creepCount = currentCreepCount;
            toSpawn.role = roleConfig;
            continue;
        }

        if (currentCreepCount < roleConfig.max) {
            if (currentCreepCount < roleConfig.min) {
                if (roleConfig.priority < toSpawn.role.priority) {
                    toSpawn.role = roleConfig;
                    toSpawn.creepCount = currentCreepCount;
                } else if (toSpawn.creepCount >= toSpawn.role.min) {
                    toSpawn.role = roleConfig;
                    toSpawn.creepCount = currentCreepCount;
                }
            } else if (roleConfig.priority < toSpawn.priority) {
                toSpawn.role = roleConfig;
                toSpawn.creepCount = currentCreepCount;
            } else if (toSpawn.creepCount === toSpawn.role.max) {
                toSpawn.role = roleConfig;
                toSpawn.creepCount = currentCreepCount;
            }
        }
    }

    if (toSpawn.creepCount < toSpawn.role.max) {
        spawnNewCreep(
            toSpawn.role.name,
            config[toSpawn.role.name].parts,
            spawner,
        );
    }
}

module.exports = checkForSpawn;
